version: '3.7'

services:

  # API
  backend:
    container_name: backend
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - '80:80'
    networks:
      - psg
    depends_on:
      - database

  # Database
  database:
    container_name: database
    image: mysql:8.0.19
    volumes:
      - ./mysql/youtube.sql:/docker-entrypoint-initdb.d/youtube.sql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER : psg
      MYSQL_PASSWORD : secret
      MYSQL_ROOT_PASSWORD : secret 
    networks:
      - psg

networks:
  psg:
    driver: bridge